/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mib.grupp12;


import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author elias
 */
public class adminpage extends javax.swing.JFrame {

    private InfDB idb;
    

    /**
     * Creates new form adminpage
     */
    public adminpage() {
        initComponents();

        try {
            idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
        } catch (InfException ex) {
            Logger.getLogger(MIBGrupp12.class.getName()).log(Level.SEVERE, null, ex);
        }
        fyllComboBox();
        fyllComboBox1();
        fyllComboBox2();
        fyllComboBox3();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtalien = new javax.swing.JTextField();
        deletealien = new javax.swing.JButton();
        txtagent = new javax.swing.JTextField();
        deleteagent = new javax.swing.JButton();
        txtutrustning = new javax.swing.JTextField();
        deleteutrustning = new javax.swing.JButton();
        changeadmin = new javax.swing.JButton();
        txtadmin = new javax.swing.JTextField();
        cbvaljalien = new javax.swing.JComboBox<>();
        cbvaljagent = new javax.swing.JComboBox<>();
        cbvaljutrustning = new javax.swing.JComboBox<>();
        cbvaljadminagent = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        deletealien.setText("DELETE ALIEN");
        deletealien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletealienActionPerformed(evt);
            }
        });

        deleteagent.setText("DELETE AGENT");
        deleteagent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteagentActionPerformed(evt);
            }
        });

        deleteutrustning.setText("DELETE UTRUSTNING");
        deleteutrustning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteutrustningActionPerformed(evt);
            }
        });

        changeadmin.setText("CHANGE TO ADMIN");
        changeadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeadminActionPerformed(evt);
            }
        });

        cbvaljalien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbvaljagent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbvaljutrustning.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbvaljadminagent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(cbvaljalien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(deleteutrustning))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(65, 65, 65)
                                        .addComponent(txtalien, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addComponent(deletealien))
                                    .addComponent(cbvaljutrustning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(146, 146, 146)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(deleteagent)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(changeadmin, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(31, 31, 31)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(cbvaljadminagent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(35, 35, 35)))
                                            .addComponent(txtagent, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(133, 133, 133)
                                        .addComponent(cbvaljagent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(txtutrustning, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(txtutrustning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(cbvaljutrustning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteutrustning)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtalien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbvaljalien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deletealien))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(txtadmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbvaljadminagent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(changeadmin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addComponent(cbvaljagent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtagent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(deleteagent)))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deletealienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletealienActionPerformed
        // TODO add your handling code here:
        /*String id = txtalien.getText();
        if (id != null) {
            try {
                String hamta = idb.fetchSingle("SELECT * FROM alien WHERE Alien_ID=" + id);
                if (hamta != null) {
                    idb.delete("DELETE FROM boglodite WHERE Alien_ID=" + id);
                    idb.delete("DELETE FROM squid WHERE Alien_ID=" + id);
                    idb.delete("DELETE FROM worm WHERE Alien_ID=" + id);
                    idb.delete("DELETE FROM alien WHERE Alien_ID=" + id);
                    JOptionPane.showMessageDialog(rootPane, "Alien är nu raderad");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Alien verkar inte finnas med i systemet");
                    txtalien.setText(null);
                }
            } catch (InfException e) {
                JOptionPane.showMessageDialog(rootPane, "Vänligen skriv in en vald alien");
            }
        }
        */
        String hamta = cbvaljalien.getSelectedItem().toString();

        try {
            String id = idb.fetchSingle("SELECT Alien_ID from alien WHERE Namn='" + hamta + "'");
            
            idb.delete("DELETE FROM boglodite WHERE Alien_ID=" + id);
            idb.delete("DELETE FROM squid WHERE Alien_ID=" + id);
            idb.delete("DELETE FROM worm WHERE Alien_ID=" + id);
            idb.delete("DELETE FROM alien WHERE Alien_ID=" + id);
            JOptionPane.showMessageDialog(rootPane, "Alien: " + hamta + " är nu raderad!");
            fyllComboBox();
            

        } catch (InfException e) {
            JOptionPane.showMessageDialog(rootPane, "funkar ej");
        }
        
    }//GEN-LAST:event_deletealienActionPerformed

   private void fyllComboBox() {
        cbvaljalien.removeAllItems();
        try {
            ArrayList<String> alienNamn = idb.fetchColumn("select namn from alien");
            for (String ettNamn : alienNamn) {
                cbvaljalien.addItem(ettNamn);
            }
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
        }
   }
    
    
    private void deleteagentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteagentActionPerformed
        // TODO add your handling code here:
        /*String id = txtagent.getText();
        String sparadEpost = datahandler.getSparadEpost();
        
        if (id != null) {
            try {
                String hamta = idb.fetchSingle("SELECT * FROM agent WHERE Agent_ID=" + id);
                String adminepost = idb.fetchSingle("SELECT Epost from agent WHERE Agent_ID=" + id);
                //String agentid = idb.fetchSingle("SELECT Epost from agent where Agent_ID="+id);
                if (hamta != null && sparadEpost != null && !sparadEpost.equals(adminepost)) {
                    idb.delete("DELETE FROM omradeschef WHERE Agent_ID=" + id);
                    idb.delete("DELETE FROM kontorschef WHERE Agent_ID=" + id);
                    idb.delete("DELETE FROM innehar_utrustning WHERE Agent_ID=" + id);
                    idb.delete("DELETE FROM faltagent WHERE Agent_ID=" + id);
                    idb.delete("DELETE FROM agent WHERE Agent_ID=" + id);
                    JOptionPane.showMessageDialog(rootPane, "Agent är nu raderad");
                    txtagent.setText(null);
                } else if (hamta != null && sparadEpost != null && sparadEpost.equals(adminepost)) {
                    JOptionPane.showMessageDialog(rootPane, "Du kan inte ta bort dig själv");
                    txtagent.setText(null);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Agent finns inte med i systemet");
                    txtagent.setText(null);
                }
            } catch (InfException e) {
                JOptionPane.showMessageDialog(rootPane, "Vänligen skriv in en vald agent");
            }
        }
        */
        String hamta = cbvaljagent.getSelectedItem().toString();
        String sparadEpost = datahandler.getSparadEpost();
        try {
            String adminepost = idb.fetchSingle("SELECT Epost from agent WHERE Namn='" + hamta + "'");
            String id = idb.fetchSingle("SELECT Agent_ID from agent WHERE Namn='" + hamta + "'");
            if (!sparadEpost.equals(adminepost)) {
                idb.delete("DELETE FROM omradeschef WHERE Agent_ID=" + id);
                idb.delete("DELETE FROM kontorschef WHERE Agent_ID=" + id);
                idb.delete("DELETE FROM innehar_utrustning WHERE Agent_ID=" + id);
                idb.delete("DELETE FROM faltagent WHERE Agent_ID=" + id);
                idb.delete("DELETE FROM agent WHERE Agent_ID=" + id);
                JOptionPane.showMessageDialog(rootPane, "Agent " + hamta +" är nu raderad");
                fyllComboBox1();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Du kan inte ta bort dig själv!");

            }

        } catch (InfException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }


    }//GEN-LAST:event_deleteagentActionPerformed

    private void fyllComboBox1() {
        cbvaljagent.removeAllItems();
        try {
            ArrayList<String> agentNamn = idb.fetchColumn("select Namn from agent");
            for (String agent : agentNamn) {
                cbvaljagent.addItem(agent);
            }
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
        }
   }
    private void deleteutrustningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteutrustningActionPerformed
        // TODO add your handling code here:
        /*String utrustning = txtutrustning.getText();
        if (utrustning != null) {
            try {
                String hamta = idb.fetchSingle("SELECT * FROM utrustning WHERE Utrustnings_ID=" + utrustning);
                if (hamta != null) {
                    
                    idb.delete("DELETE FROM innehar_utrustning WHERE Utrustnings_ID=" + utrustning);
                    idb.delete("DELETE FROM kommunikation WHERE Utrustnings_ID=" + utrustning);
                    idb.delete("DELETE FROM teknik WHERE Utrustnings_ID=" + utrustning);
                    idb.delete("DELETE FROM vapen WHERE Utrustnings_ID=" + utrustning);
                    idb.delete("DELETE FROM utrustning WHERE Utrustnings_ID=" + utrustning);
                    JOptionPane.showMessageDialog(rootPane, "Utrustning är nu raderad");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Finns ingen utrustning med det namnet");
                    txtutrustning.setText(null);
                }
                
            } catch (InfException e) {
                JOptionPane.showMessageDialog(rootPane, "Vänligen skriv in utrustning");
            }
        }
        */
        String hamta = cbvaljutrustning.getSelectedItem().toString();
        
        try {
            String utrustning = idb.fetchSingle("SELECT Utrustnings_ID FROM utrustning WHERE Benamning='" + hamta + "'");
            
            idb.delete("DELETE FROM innehar_utrustning WHERE Utrustnings_ID=" + utrustning);
            idb.delete("DELETE FROM kommunikation WHERE Utrustnings_ID=" + utrustning);
            idb.delete("DELETE FROM teknik WHERE Utrustnings_ID=" + utrustning);
            idb.delete("DELETE FROM vapen WHERE Utrustnings_ID=" + utrustning);
            idb.delete("DELETE FROM utrustning WHERE Utrustnings_ID=" + utrustning);
            JOptionPane.showMessageDialog(rootPane, "Utrustning är nu raderad");            
            fyllComboBox2();
        } catch (InfException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        
        
    }//GEN-LAST:event_deleteutrustningActionPerformed

    private void fyllComboBox2() {
        cbvaljutrustning.removeAllItems();
        try {
            ArrayList<String> utrustning = idb.fetchColumn("SELECT Benamning FROM utrustning");
            for (String sak : utrustning) {
                cbvaljutrustning.addItem(sak);
            }
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
        }
   }
    
    private void changeadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeadminActionPerformed
        // TODO add your handling code here:
        /*String nyadmin = txtadmin.getText();
        if (nyadmin != null) {
            try {
                String hamta = idb.fetchSingle("SELECT * FROM agent WHERE Agent_ID=" + nyadmin);
                String status = idb.fetchSingle("SELECT Administrator from agent where Agent_ID=" + nyadmin);
                if (hamta != null && status.equals("N")) {
                    idb.update("UPDATE agent SET Administrator='J' WHERE Agent_ID=" + hamta);
                    JOptionPane.showMessageDialog(rootPane, "Agenten är nu en admin");
                    
                } else if (hamta != null && status.equals("J")) {
                    JOptionPane.showMessageDialog(rootPane, "Agenten är redan admin");
                    txtadmin.setText(null);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Agenten verkar inte finnas med i systemet");
                    txtadmin.setText(null);
                }
            } catch (InfException e) {
                JOptionPane.showMessageDialog(rootPane, e);
            }
        }
        */
        
        String hamta = cbvaljadminagent.getSelectedItem().toString();
        try {
            idb.update("UPDATE agent SET Administrator='J' WHERE Namn='" + hamta + "'");
            JOptionPane.showMessageDialog(rootPane, "Agent " + hamta+ " är nu admin");
            fyllComboBox3();

        } catch (InfException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        
    }//GEN-LAST:event_changeadminActionPerformed

    private void fyllComboBox3() {
        cbvaljadminagent.removeAllItems();
        try {
            ArrayList<String> agent = idb.fetchColumn("SELECT Namn FROM agent WHERE Administrator = 'N'");
            for (String admin : agent) {
                cbvaljadminagent.addItem(admin);
            }
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
        }
   }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbvaljadminagent;
    private javax.swing.JComboBox<String> cbvaljagent;
    private javax.swing.JComboBox<String> cbvaljalien;
    private javax.swing.JComboBox<String> cbvaljutrustning;
    private javax.swing.JButton changeadmin;
    private javax.swing.JButton deleteagent;
    private javax.swing.JButton deletealien;
    private javax.swing.JButton deleteutrustning;
    private javax.swing.JTextField txtadmin;
    private javax.swing.JTextField txtagent;
    private javax.swing.JTextField txtalien;
    private javax.swing.JTextField txtutrustning;
    // End of variables declaration//GEN-END:variables
}
