/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mib.grupp12;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author elias
 */
public class adminandraagentinfo extends javax.swing.JFrame {

    private InfDB idb;

    /**
     * Creates new form adminandraagentinfo
     */
    public adminandraagentinfo() {
        initComponents();
        try {
            idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
        } catch (InfException ex) {
            Logger.getLogger(MIBGrupp12.class.getName()).log(Level.SEVERE, null, ex);
        }
        fyllComboBox4();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void andranamn() {
        String hamta = cbvaljagentinfo.getSelectedItem().toString();
        try {
            if (Validering.TextHarFaltVarde(txtid)) {
                String Namn = txtid.getText();
                idb.update("UPDATE agent SET Namn='" + Namn + "' WHERE Namn='" + hamta + "'");
                JOptionPane.showMessageDialog(rootPane, "Agent namn är nu ändrad");
                txtid.setText(null);
                fyllComboBox4();
            }
        } catch (InfException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }

    private void andratelefon() {
        String hamta = cbvaljagentinfo.getSelectedItem().toString();
        try {
            if (Validering.TextHarFaltVarde(txttelefon) && Validering.isHeltal(txttelefon)) {
                String telefon = txttelefon.getText();
                idb.update("UPDATE agent SET Telefon='" + telefon + "' WHERE Namn='" + hamta + "'");
                JOptionPane.showMessageDialog(rootPane, "Agent telefon är nu ändrad");
                txttelefon.setText(null);

            }

        } catch (InfException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }

    private void andraanstallningsdatum() {
        String hamta = cbvaljagentinfo.getSelectedItem().toString();
        try {
            if (Validering.TextHarFaltVarde(txtanstallningsdatum)) {
                String datum = txtanstallningsdatum.getText();
                idb.update("UPDATE agent SET Anstallningsdatum='" + datum + "' WHERE Namn='" + hamta + "'");
                JOptionPane.showMessageDialog(rootPane, "Agent datum är nu ändrad");
                txtanstallningsdatum.setText(null);

            }

        } catch (InfException e) {
            JOptionPane.showMessageDialog(rootPane, "Ange i formar xxxx-xx-xx");
        }
    }

    private void andraepost() {
        String hamta = cbvaljagentinfo.getSelectedItem().toString();
        try {
            if (Validering.TextHarFaltVarde(txtepost)) {
                String epost = txtepost.getText();
                idb.update("UPDATE agent SET Epost='" + epost + "' WHERE Namn='" + hamta + "'");
                JOptionPane.showMessageDialog(rootPane, "Agent epost är nu ändrad");
                txtepost.setText(null);

            }

        } catch (InfException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }

    private void andralosenord() {
        String hamta = cbvaljagentinfo.getSelectedItem().toString();
        try {
            if (Validering.TextHarFaltVarde(txtandralosenord)) {
                String nyttlosen = txtandralosenord.getText();
                idb.update("UPDATE agent SET Losenord='" + nyttlosen + "' WHERE Namn='" + hamta + "'");
                JOptionPane.showMessageDialog(rootPane, "Agent lösen är nu ändrad");
                txtandralosenord.setText(null);

            }

        } catch (InfException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }

    private void andraomrade() {
        String hamta = cbvaljagentinfo.getSelectedItem().toString();
        try {
            if (Validering.TextHarFaltVarde(txtomrade) && Validering.isHeltal(txtomrade)) {
                String nyttomrade = txtomrade.getText();
                idb.update("UPDATE agent SET Omrade='" + nyttomrade + "' WHERE Namn='" + hamta + "'");
                JOptionPane.showMessageDialog(rootPane, "Agent omrade är nu ändrad");
                txtomrade.setText(null);

            }

        } catch (InfException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbvaljagentinfo = new javax.swing.JComboBox<>();
        txtid = new javax.swing.JTextField();
        andranamn = new javax.swing.JButton();
        txttelefon = new javax.swing.JTextField();
        andratelefon = new javax.swing.JButton();
        andraanstallningsdatum = new javax.swing.JButton();
        txtanstallningsdatum = new javax.swing.JTextField();
        txtepost = new javax.swing.JTextField();
        andraepost = new javax.swing.JButton();
        txtandralosenord = new javax.swing.JTextField();
        andralosenord = new javax.swing.JButton();
        txtomrade = new javax.swing.JTextField();
        andraområde = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbvaljagentinfo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        andranamn.setText("ändra namn");
        andranamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                andranamnActionPerformed(evt);
            }
        });

        andratelefon.setText("ändra telefon");
        andratelefon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                andratelefonActionPerformed(evt);
            }
        });

        andraanstallningsdatum.setText("ändra anstallningsdatum");
        andraanstallningsdatum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                andraanstallningsdatumActionPerformed(evt);
            }
        });

        andraepost.setText("ändra epost");
        andraepost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                andraepostActionPerformed(evt);
            }
        });

        andralosenord.setText("ändra lösenord");
        andralosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                andralosenordActionPerformed(evt);
            }
        });

        andraområde.setText("ändra område");
        andraområde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                andraområdeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(cbvaljagentinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(andranamn))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txttelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtanstallningsdatum, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtepost, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtandralosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtomrade, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(andraanstallningsdatum)
                                    .addComponent(andratelefon)
                                    .addComponent(andraepost)
                                    .addComponent(andralosenord)
                                    .addComponent(andraområde))))))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(cbvaljagentinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(andranamn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(andratelefon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(andraanstallningsdatum)
                    .addComponent(txtanstallningsdatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtepost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(andraepost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtandralosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(andralosenord))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtomrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(andraområde))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void andranamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_andranamnActionPerformed
        // TODO add your handling code here:
        andranamn();
    }//GEN-LAST:event_andranamnActionPerformed

    private void andratelefonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_andratelefonActionPerformed
        // TODO add your handling code here:
        andratelefon();
    }//GEN-LAST:event_andratelefonActionPerformed

    private void andraanstallningsdatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_andraanstallningsdatumActionPerformed
        // TODO add your handling code here:
        andraanstallningsdatum();
    }//GEN-LAST:event_andraanstallningsdatumActionPerformed

    private void andraepostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_andraepostActionPerformed
        // TODO add your handling code here:
        andraepost();
    }//GEN-LAST:event_andraepostActionPerformed

    private void andralosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_andralosenordActionPerformed
        // TODO add your handling code here:
        andralosenord();
    }//GEN-LAST:event_andralosenordActionPerformed

    private void andraområdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_andraområdeActionPerformed
        // TODO add your handling code here:
        andraomrade();
    }//GEN-LAST:event_andraområdeActionPerformed
    private void fyllComboBox4() {
        cbvaljagentinfo.removeAllItems();
        try {
            ArrayList<String> agentNamn = idb.fetchColumn("select Namn from agent");
            for (String agent : agentNamn) {
                cbvaljagentinfo.addItem(agent);
            }
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
        }
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton andraanstallningsdatum;
    private javax.swing.JButton andraepost;
    private javax.swing.JButton andralosenord;
    private javax.swing.JButton andranamn;
    private javax.swing.JButton andraområde;
    private javax.swing.JButton andratelefon;
    private javax.swing.JComboBox<String> cbvaljagentinfo;
    private javax.swing.JTextField txtandralosenord;
    private javax.swing.JTextField txtanstallningsdatum;
    private javax.swing.JTextField txtepost;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtomrade;
    private javax.swing.JTextField txttelefon;
    // End of variables declaration//GEN-END:variables
}
