/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mib.grupp12;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author elias
 */
public class adminpage extends javax.swing.JFrame {

    private InfDB idb;

    /**
     * Creates new form adminpage
     */
    public adminpage() {
        initComponents();

        try {
            idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
        } catch (InfException ex) {
            Logger.getLogger(MIBGrupp12.class.getName()).log(Level.SEVERE, null, ex);
        }
        fyllComboBox();
        fyllComboBox1();
        fyllComboBox2();
        fyllComboBox3();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deletealien = new javax.swing.JButton();
        deleteagent = new javax.swing.JButton();
        deleteutrustning = new javax.swing.JButton();
        changeadmin = new javax.swing.JButton();
        cbvaljalien = new javax.swing.JComboBox<>();
        cbvaljagent = new javax.swing.JComboBox<>();
        cbvaljutrustning = new javax.swing.JComboBox<>();
        cbvaljadminagent = new javax.swing.JComboBox<>();
        changeagentinfo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        deletealien.setText("DELETE ALIEN");
        deletealien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletealienActionPerformed(evt);
            }
        });

        deleteagent.setText("DELETE AGENT");
        deleteagent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteagentActionPerformed(evt);
            }
        });

        deleteutrustning.setText("DELETE UTRUSTNING");
        deleteutrustning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteutrustningActionPerformed(evt);
            }
        });

        changeadmin.setText("CHANGE TO ADMIN");
        changeadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeadminActionPerformed(evt);
            }
        });

        cbvaljalien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbvaljagent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbvaljutrustning.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbvaljadminagent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        changeagentinfo.setText("CHANGE INFO AGENT");
        changeagentinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeagentinfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(cbvaljalien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbvaljagent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(deletealien))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(deleteutrustning))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(cbvaljutrustning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(deleteagent)
                                    .addComponent(changeadmin)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addComponent(cbvaljadminagent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(changeagentinfo)
                .addGap(161, 161, 161))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbvaljutrustning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbvaljadminagent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteutrustning)
                    .addComponent(changeadmin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(changeagentinfo)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cbvaljalien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deletealien))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cbvaljagent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteagent)))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deletealienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletealienActionPerformed
        String hamta = cbvaljalien.getSelectedItem().toString();

        try {
            String id = idb.fetchSingle("SELECT Alien_ID from alien WHERE Namn='" + hamta + "'");

            idb.delete("DELETE FROM boglodite WHERE Alien_ID=" + id);
            idb.delete("DELETE FROM squid WHERE Alien_ID=" + id);
            idb.delete("DELETE FROM worm WHERE Alien_ID=" + id);
            idb.delete("DELETE FROM alien WHERE Alien_ID=" + id);
            JOptionPane.showMessageDialog(rootPane, "Alien: " + hamta + " är nu raderad!");
            fyllComboBox();

        } catch (InfException e) {
            JOptionPane.showMessageDialog(rootPane, "funkar ej");
        }

    }//GEN-LAST:event_deletealienActionPerformed

    private void fyllComboBox() {
        cbvaljalien.removeAllItems();
        try {
            ArrayList<String> alienNamn = idb.fetchColumn("select namn from alien");
            for (String ettNamn : alienNamn) {
                cbvaljalien.addItem(ettNamn);
            }
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
        }
    }

 
    private void deleteutrustningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteutrustningActionPerformed
        // TODO add your handling code here:
        
        String hamta = cbvaljutrustning.getSelectedItem().toString();

        try {
            String utrustning = idb.fetchSingle("SELECT Utrustnings_ID FROM utrustning WHERE Benamning='" + hamta + "'");

            idb.delete("DELETE FROM innehar_utrustning WHERE Utrustnings_ID=" + utrustning);
            idb.delete("DELETE FROM kommunikation WHERE Utrustnings_ID=" + utrustning);
            idb.delete("DELETE FROM teknik WHERE Utrustnings_ID=" + utrustning);
            idb.delete("DELETE FROM vapen WHERE Utrustnings_ID=" + utrustning);
            idb.delete("DELETE FROM utrustning WHERE Utrustnings_ID=" + utrustning);
            JOptionPane.showMessageDialog(rootPane, "Utrustning är nu raderad");
            fyllComboBox2();
        } catch (InfException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }


    }//GEN-LAST:event_deleteutrustningActionPerformed

    private void fyllComboBox2() {
        cbvaljutrustning.removeAllItems();
        try {
            ArrayList<String> utrustning = idb.fetchColumn("SELECT Benamning FROM utrustning");
            for (String sak : utrustning) {
                cbvaljutrustning.addItem(sak);
            }
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
        }
    }

    private void changeadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeadminActionPerformed
        // TODO add your handling code here:
       
        String hamta = cbvaljadminagent.getSelectedItem().toString();
        try {
            idb.update("UPDATE agent SET Administrator='J' WHERE Namn='" + hamta + "'");
            JOptionPane.showMessageDialog(rootPane, "Agent " + hamta + " är nu admin");
            fyllComboBox3();

        } catch (InfException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }

    }//GEN-LAST:event_changeadminActionPerformed

    private void fyllComboBox3() {
        cbvaljadminagent.removeAllItems();
        try {
            ArrayList<String> agent = idb.fetchColumn("SELECT Namn FROM agent WHERE Administrator = 'N'");
            for (String admin : agent) {
                cbvaljadminagent.addItem(admin);
            }
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
        }
    }
  
    private void deleteagentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteagentActionPerformed
        // TODO add your handling code here:
        String hamta = cbvaljagent.getSelectedItem().toString();
        String sparadEpost = datahandler.getSparadEpost();

        try {
            String id = idb.fetchSingle("SELECT Agent_ID FROM agent WHERE Namn='" + hamta + "'");
            String epost = idb.fetchSingle("SELECT Epost FROM agent WHERE Namn='" + hamta + "'");
            String alienid = idb.fetchSingle("SELECT Ansvarig_Agent FROM alien WHERE Ansvarig_Agent='" + id + "'");
            if (epost != null && !epost.equals(sparadEpost) && alienid != null && alienid.equals(id)) {
                // Agenten ansvarar för en alien, överför ansvaret till en annan agent
                JOptionPane.showMessageDialog(rootPane, "Agenten du försöker ta bort ansvarar för en alien, överför ansvaret till en annan agent");
            } else if (epost != null && !epost.equals(sparadEpost) && (alienid == null || !alienid.equals(id))) {
                // Ta bort agenten
                idb.delete("DELETE FROM omradeschef WHERE Agent_ID=" + id);
                idb.delete("DELETE FROM kontorschef WHERE Agent_ID=" + id);
                idb.delete("DELETE FROM innehar_utrustning WHERE Agent_ID=" + id);
                idb.delete("DELETE FROM faltagent WHERE Agent_ID=" + id);
                idb.delete("DELETE FROM agent WHERE Agent_ID=" + id);

                JOptionPane.showMessageDialog(rootPane, "Agent " + hamta + " är nu borttagen!");
                fyllComboBox1();
                fyllComboBox3();
            } else {
                // Du kan inte ta bort dig själv eller ingen matchning hittades
                JOptionPane.showMessageDialog(rootPane, "Du kan inte ta bort dig själv eller ingen matchning hittades");
            }

        } catch (InfException e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }


    }//GEN-LAST:event_deleteagentActionPerformed

    private void fyllComboBox1() {
        cbvaljagent.removeAllItems();
        try {
            ArrayList<String> agentNamn = idb.fetchColumn("select Namn from agent");
            for (String agent : agentNamn) {
                cbvaljagent.addItem(agent);
            }
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
        }
    }
    
    private void changeagentinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeagentinfoActionPerformed
        // TODO add your handling code here:
       adminandraagentinfo ad = new adminandraagentinfo();
       ad.show();
       dispose();
    }//GEN-LAST:event_changeagentinfoActionPerformed
 

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbvaljadminagent;
    private javax.swing.JComboBox<String> cbvaljagent;
    private javax.swing.JComboBox<String> cbvaljalien;
    private javax.swing.JComboBox<String> cbvaljutrustning;
    private javax.swing.JButton changeadmin;
    private javax.swing.JButton changeagentinfo;
    private javax.swing.JButton deleteagent;
    private javax.swing.JButton deletealien;
    private javax.swing.JButton deleteutrustning;
    // End of variables declaration//GEN-END:variables
}
