/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mib.grupp12;
import java.util.logging.Level;
import java.util.logging.Logger;
import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.*;
 /*
 * @author dianazakholi
 */
public class AgentLogin extends javax.swing.JFrame {
  private InfDB idb; 
    /**
     * Creates new form AgentLogin
     */
    public AgentLogin() {
        initComponents();

        try {
           idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
       } catch (InfException ex) {
           Logger.getLogger(MIBGrupp12.class.getName()).log(Level.SEVERE, null, ex);
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WelcomelabelAG = new javax.swing.JLabel();
        angeEpost = new javax.swing.JTextField();
        EmailLabel = new javax.swing.JLabel();
        PassLabel = new javax.swing.JLabel();
        AGlabelinfo = new javax.swing.JLabel();
        EnterButtonAG = new javax.swing.JButton();
        angeLosenAG = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        WelcomelabelAG.setFont(new java.awt.Font("Phosphate", 1, 48)); // NOI18N
        WelcomelabelAG.setText("Welcome");

        EmailLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        EmailLabel.setText("E-mail adress:");

        PassLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        PassLabel.setText("Password:");

        AGlabelinfo.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        AGlabelinfo.setText("Log in using your Agent credentials");

        EnterButtonAG.setText("Enter");
        EnterButtonAG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterButtonAGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PassLabel)
                            .addComponent(EmailLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(angeEpost, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                            .addComponent(angeLosenAG)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WelcomelabelAG, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AGlabelinfo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(EnterButtonAG)))
                .addContainerGap(255, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(WelcomelabelAG, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AGlabelinfo)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(angeEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailLabel))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PassLabel)
                    .addComponent(angeLosenAG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(EnterButtonAG)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnterButtonAGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterButtonAGActionPerformed
        // TODO add your handling code here:
String epost = angeEpost.getText();
char[] charLosenord = angeLosenAG.getPassword();
String losenord = new String(charLosenord);

try {
    String sqlFraga = "SELECT losenord FROM agent WHERE Epost ='" + epost + "'";
    String getAgentID = "SELECT Agent_ID FROM agent WHERE Epost = '" + epost + "'";
    String agentID = idb.fetchSingle(getAgentID);
    String sqlFragaAdmin = "SELECT Administrator FROM agent WHERE Agent_ID = " + agentID;
    String sqlSvarLosenord = idb.fetchSingle(sqlFraga);
    String sqlSvarAdmin = idb.fetchSingle(sqlFragaAdmin);
    
    if (sqlSvarLosenord != null && losenord.equals(sqlSvarLosenord) && sqlSvarAdmin.equals("N")) {
       
      AgentPage ap = new AgentPage();
        ap.show();
        
        dispose();
      
        
    } else if (sqlSvarLosenord != null && losenord.equals(sqlSvarLosenord) && sqlSvarAdmin.equals("J")){
        JOptionPane.showMessageDialog(null, "Du är en administratör, byt inloggning till administratör.");
    mittfönster start = new mittfönster();
    start.show();
    
    dispose();
    
    }
            else 
    {
            JOptionPane.showMessageDialog(null, "E-post eller lösenord är felaktigt.");
            angeEpost.setText(null);
            angeLosenAG.setText(null);
}
    }
    catch (InfException e){
            System.out.println("fel" + e.getMessage());
}
        
    
    }//GEN-LAST:event_EnterButtonAGActionPerformed
  
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AGlabelinfo;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JButton EnterButtonAG;
    private javax.swing.JLabel PassLabel;
    private javax.swing.JLabel WelcomelabelAG;
    private javax.swing.JTextField angeEpost;
    private javax.swing.JPasswordField angeLosenAG;
    // End of variables declaration//GEN-END:variables
}
