/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mib.grupp12;

/**
 *
 * @author dianazakholi
 */
public class AgentLogin extends javax.swing.JFrame {

    /**
     * Creates new form AgentLogin
     */
    public AgentLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtAgentemail = new javax.swing.JTextField();
        lblAgentlogin = new javax.swing.JLabel();
        pwdAgentpwd = new javax.swing.JPasswordField();
        btnAgentSignin = new javax.swing.JButton();
        lblAgentusn = new javax.swing.JLabel();
        lblAgentpwd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 255, 204), new java.awt.Color(0, 255, 204), new java.awt.Color(0, 255, 204), new java.awt.Color(0, 255, 204)));

        txtAgentemail.setBackground(new java.awt.Color(0, 255, 204));
        txtAgentemail.setFont(new java.awt.Font("PT Mono", 0, 13)); // NOI18N
        txtAgentemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgentemailActionPerformed(evt);
            }
        });

        lblAgentlogin.setFont(new java.awt.Font("PT Mono", 1, 24)); // NOI18N
        lblAgentlogin.setForeground(new java.awt.Color(0, 255, 204));
        lblAgentlogin.setText("AGENT LOGIN");

        pwdAgentpwd.setBackground(new java.awt.Color(0, 255, 204));
        pwdAgentpwd.setFont(new java.awt.Font("PT Mono", 0, 13)); // NOI18N
        pwdAgentpwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdAgentpwdActionPerformed(evt);
            }
        });

        btnAgentSignin.setBackground(new java.awt.Color(0, 255, 204));
        btnAgentSignin.setFont(new java.awt.Font("PT Mono", 0, 13)); // NOI18N
        btnAgentSignin.setText("SIGN IN");

        lblAgentusn.setFont(new java.awt.Font("PT Mono", 0, 13)); // NOI18N
        lblAgentusn.setForeground(new java.awt.Color(0, 255, 204));
        lblAgentusn.setText("Username");

        lblAgentpwd.setFont(new java.awt.Font("PT Mono", 0, 13)); // NOI18N
        lblAgentpwd.setForeground(new java.awt.Color(0, 255, 204));
        lblAgentpwd.setText("Password");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAgentusn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAgentpwd, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAgentSignin)
                            .addComponent(txtAgentemail)
                            .addComponent(pwdAgentpwd, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(lblAgentlogin)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblAgentlogin)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAgentemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAgentusn, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwdAgentpwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAgentpwd, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAgentSignin)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pwdAgentpwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdAgentpwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdAgentpwdActionPerformed

    private void txtAgentemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgentemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgentemailActionPerformed

    /* Create and display the form */
    public void run() {
        new AgentLogin().setVisible(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgentSignin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAgentlogin;
    private javax.swing.JLabel lblAgentpwd;
    private javax.swing.JLabel lblAgentusn;
    private javax.swing.JPasswordField pwdAgentpwd;
    private javax.swing.JTextField txtAgentemail;
    // End of variables declaration//GEN-END:variables
}
