/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mib.grupp12;
import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.*;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author dianazakholi
 */
public class AndraLosenAG extends javax.swing.JFrame {
   private InfDB idb;
    /**
     * Creates new form AndraLosenAG
     */
    public AndraLosenAG() {
        initComponents();
        
        try {
           idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
       } catch (InfException ex) {
           Logger.getLogger(MIBGrupp12.class.getName()).log(Level.SEVERE, null, ex);
       }

    
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        enterNewP = new javax.swing.JPasswordField();
        EnterNewPass = new javax.swing.JButton();
        eposttxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("Change your password");

        jLabel2.setFont(new java.awt.Font("ITF Devanagari", 2, 14)); // NOI18N
        jLabel2.setText("Confirm your e-mail and proceed to enter your new password.");

        jLabel3.setFont(new java.awt.Font("ITF Devanagari", 3, 13)); // NOI18N
        jLabel3.setText("E-mail:");

        jLabel4.setFont(new java.awt.Font("ITF Devanagari", 3, 13)); // NOI18N
        jLabel4.setText("New password:");

        EnterNewPass.setText("Enter");
        EnterNewPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterNewPassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 67, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(175, 175, 175))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(eposttxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enterNewP))
                        .addGap(376, 376, 376))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(EnterNewPass))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel2)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(eposttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(enterNewP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(EnterNewPass)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnterNewPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterNewPassActionPerformed
        // TODO add your handling code here:
          //String newPass = enterNewP.getText();
         // String oldPass = OldPass.getText();
          
           // String fraga = "UPDATE agent SET Losenord = '" + newPass + "' WHERE Epost = '" + epost + "'";
           // String sqlfraga = "SELECT losenord from AGENT where Epost ='"+epost+"'";
          //  try {
          //    String correctPass = idb.fetchSingle(sqlfraga); 
           //   if (correctPass.equals(oldPass) && !epost.isEmpty()) {
             //     idb.update(fraga);
                
            //  }
            
          // else {
         //   }
         //   idb.update(fraga);
        //    JOptionPane.showMessageDialog(rootPane, "Ditt lösenord har uppdaterats.");
            
        //} catch (InfException e) {
        //    JOptionPane.showMessageDialog(rootPane, "Något gick fel!"+ e);
     //   }    
  try {
            idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
                        
            String epost = eposttxt.getText();
            String nyttLosen = enterNewP.getText();
            
            String fraga = "UPDATE alien SET Losenord = '" + nyttLosen + "' WHERE Epost = '" + epost + "'";
            
            if (nyttLosen.isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "Fyll i ditt nya lösenord!");
            } else {
            }
            idb.update(fraga);
            JOptionPane.showMessageDialog(rootPane, "Ditt lösenord har uppdaterats!");
               
      AgentPage ap = new AgentPage();
        ap.show();
        
        dispose();
            
        } catch (InfException e) {
            JOptionPane.showMessageDialog(rootPane, "Något gick fel!"+ e);
        }               
    }//GEN-LAST:event_EnterNewPassActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EnterNewPass;
    private javax.swing.JPasswordField enterNewP;
    private javax.swing.JTextField eposttxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
