/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mib.grupp12;

import oru.inf.InfDB;

/**
 *
 * @author elias
 */
public class mittfönster extends javax.swing.JFrame {

    private InfDB idb;

    /**
     * Creates new form mittfönster
     */
    public mittfönster() {
        initComponents();
        this.idb = idb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ChoiceLabel = new javax.swing.JLabel();
        AgentLogin = new javax.swing.JButton();
        AlienLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ChoiceLabel.setText("Log in as Agent or Alien");

        AgentLogin.setText("Agent");
        AgentLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgentLoginActionPerformed(evt);
            }
        });

        AlienLogin.setText("Alien");
        AlienLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlienLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(AgentLogin)
                        .addGap(64, 64, 64)
                        .addComponent(AlienLogin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(ChoiceLabel)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(ChoiceLabel)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgentLogin)
                    .addComponent(AlienLogin))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgentLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgentLoginActionPerformed
        AgentLogin aglogin = new AgentLogin();
        aglogin.show();
        dispose();
    }//GEN-LAST:event_AgentLoginActionPerformed

    private void AlienLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlienLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlienLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgentLogin;
    private javax.swing.JButton AlienLogin;
    private javax.swing.JLabel ChoiceLabel;
    // End of variables declaration//GEN-END:variables
}
